name: Coding Standards

on:
  pull_request:
    branches:
      - main

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: 8.3
          tools: composer:v2,cs2pr

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v3
        with:
          composer-options: --prefer-dist --optimize-autoloader

      - name: Check code style
        run: composer phpcs -- --format=checkstyle | cs2pr
